[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = ["forge-std/=lib/forge-std/src/"]

# Allow scripts to write deployment addresses
fs_permissions = [{ access = "read-write", path = "./addresses.json" }]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
